name: todo_app_ui_example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  #firebase
  firebase_core: ^1.2.0
  cloud_firestore: ^2.2.0

  # state management
  provider: ^5.0.0

  # slidable
  flutter_slidable: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true